field_names = {
    'TRAFFIC': {
        0: 'FUTURE_USE 0',
        1: 'Receive Time',
        2: 'Serial Number',
        3: 'Log type',
        4: 'Threat/Content Type',
        5: 'Firewall id',  # Future use
        6: 'Generated time',
        7: 'Source address',
        8: 'Destination address',
        9: 'NAT source IP',
        10: 'NAT destination IP',
        11: 'Rule',
        12: 'Source user',
        13: 'Destination user',
        14: 'Application',
        15: 'Virtual system',
        16: 'Source Zone',
        17: 'Destination Zone',
        18: 'Inbound Interface',
        19: 'Outbound Interface',
        20: 'Log Action',
        21: 'FUTURE_USE 21',
        22: 'Session ID',
        23: 'Repeat Count',
        24: 'Source Port',
        25: 'Destination Port',
        26: 'NAT Source Port',
        27: 'NAT Destination Port',
        28: 'Flags',
        29: 'IP Protocol',
        30: 'Action',
        31: 'Bytes',
        32: 'Bytes Sent',
        33: 'Bytes Received',
        34: 'Packets',
        35: 'Start Time',
        36: 'Elapsed Time',
        37: 'Category',
        38: 'FUTURE_USE 38',
        39: 'Sequence Number',
        40: 'Action Flags',
        41: 'Source Country',
        42: 'Destination Country',
        43: 'FUTURE_USE 43',
        44: 'Packets Sent',
        45: 'Packets Received',
        46: 'Session End Reason',
        47: 'Device Group Hierarchy Level 1',
        48: 'Device Group Hierarchy Level 2',
        49: 'Device Group Hierarchy Level 3',
        50: 'Device Group Hierarchy Level 4',
        51: 'Virtual System Name',
        52: 'Device name',
        53: 'Action Source',
        54: 'Source VM UUID',
        55: 'Destination VM UUID',
        56: 'Tunnel ID/IMSI',
        57: 'Monitor Tag/IMEI',
        58: 'Parent Session ID',
        59: 'Parent Start Time',
        60: 'Tunnel Type',
        61: 'SCTP Association ID',
        62: 'SCTP Chunks',
        63: 'SCTP Chunks Sent',
        64: 'SCTP Chunks Received',
        65: 'Rule UUID',
        66: 'HTTP/2 Connection',
        67: 'App Flap Count',
        68: 'Policy ID',
        69: 'Link Switches',
        70: 'SD-WAN Cluster',
        71: 'SD-WAN Device Type',
        72: 'SD-WAN Cluster Type',
        73: 'SD-WAN Site',
        74: 'Dynamic User Group Name',
        75: 'XFF Address',
        76: 'Source Device Category',
        77: 'Source Device Profile',
        78: 'Source Device Model',
        79: 'Source Device Vendor',
        80: 'Source Device OS Family',
        81: 'Source Device OS Version',
        82: 'Source Hostname',
        83: 'Source Mac Address',
        84: 'Destination Device Category',
        85: 'Destination Device Profile',
        86: 'Destination Device Model',
        87: 'Destination Device Vendor',
        88: 'Destination Device OS Family',
        89: 'Destination Device OS Version',
        90: 'Destination Hostname',
        91: 'Destination Mac Address',
        92: 'Container ID',
        93: 'POD Namespace',
        94: 'POD Name',
        95: 'Source External Dynamic List',
        96: 'Destination External Dynamic List',
        97: 'Host ID',
        98: 'Serial Number',
        99: 'Source Dynamic Address Group',
        100: 'Destination Dynamic Address Group',
        101: 'Session Owner',
        102: 'High Resolution Timestamp',
        103: 'A Slice Service Type',
        104: 'A Slice Differentiator',
        105: 'App Subcategory',
        106: 'App Category',
        107: 'App Technology',
        108: 'App Risk',
        109: 'App Characteristic',
        110: 'Application Container',
        111: 'Tunneled Application',
        112: 'Application SaaS',
        113: 'Application Sanctioned State',
        114: 'Offloaded',
        115: 'Flow Type',
        116: 'Cluster Name',
    },
    'SYSTEM': {
        0: 'FUTURE_USE 0',
        1: 'Receive Time',
        2: 'Serial Number',
        3: 'Log type',
        4: 'Threat/Content Type',
        5: 'Firewall id',  # Future use
        6: 'Generated time',
        7: 'Virtual System',
        8: 'Event ID',
        9: 'Object',
        10: 'FUTURE_USE 10',
        11: 'FUTURE_USE 11',
        12: 'Module',
        13: 'Severity',
        14: 'Description',
        15: 'Sequence Number',
        16: 'Action Flags',
        17: 'Device Group Hierarchy Level 1',
        18: 'Device Group Hierarchy Level 2',
        19: 'Device Group Hierarchy Level 3',
        20: 'Device Group Hierarchy Level 4',
        21: 'Virtual System Name',
        22: 'Device Name',
        23: 'FUTURE_USE',
        24: 'FUTURE_USE',
        25: 'High Resolution Timestamp',
    }
}
